# Generated by Django 4.1.7 on 2023-04-30 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_open', models.DateTimeField()),
                ('date_close', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Resevation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_of_velo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='velo',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Alocation_Velo',
        ),
        migrations.AddField(
            model_name='resevation',
            name='velo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='velo_located', to='api.velo'),
        ),
        migrations.AddField(
            model_name='location',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_alocate', to='api.resevation'),
        ),
    ]
