# Generated by Django 4.1.7 on 2023-04-23 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='velo',
            name='date_close',
        ),
        migrations.RemoveField(
            model_name='velo',
            name='date_open',
        ),
        migrations.RemoveField(
            model_name='velo',
            name='user',
        ),
        migrations.CreateModel(
            name='Alocation_Velo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_open', models.DateTimeField()),
                ('date_close', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_of_velo', to=settings.AUTH_USER_MODEL)),
                ('velo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='velo_located', to='api.velo')),
            ],
        ),
    ]
