# Generated by Django 4.1.7 on 2023-03-03 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pos_User',
        ),
    ]
