# Generated by Django 4.1.7 on 2023-07-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Photo',
            field=models.FileField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='Nom_struc',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
