# Generated by Django 4.1.7 on 2023-04-30 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_location_resevation_alter_velo_state_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resevation',
            new_name='Reservation',
        ),
    ]
