# Generated by Django 4.1.7 on 2023-07-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_employee_photo_alter_structure_nom_struc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
