# Generated by Django 4.1.7 on 2023-03-03 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_pos_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pos_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_of_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
