# Generated by Django 4.1.7 on 2023-07-24 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Echelle',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='Id_struc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.structure'),
        ),
    ]
