# Generated by Django 4.1.7 on 2023-04-30 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_velo_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='date_close',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_of_velo', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='velo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='velo_located', to='api.velo', unique=True),
        ),
    ]
