# Generated by Django 4.1.7 on 2023-03-04 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_pos_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos_user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pos_of_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
