# Generated by Django 4.1.7 on 2023-07-24 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_offreemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreemp',
            name='Id_dep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.departement'),
        ),
        migrations.AddField(
            model_name='offreemp',
            name='Id_struc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.structure'),
        ),
    ]
