# Generated by Django 4.1.7 on 2023-04-30 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_location_date_close_alter_reservation_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_of_velo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='velo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='velo_located', to='api.velo'),
        ),
    ]
