# Generated by Django 4.1.7 on 2023-04-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_pos_user_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Velo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=15)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Lock',
        ),
        migrations.AddField(
            model_name='user',
            name='sold',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
