# Generated by Django 4.1.7 on 2023-04-06 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_velo_delete_lock_user_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='matricule',
        ),
        migrations.RemoveField(
            model_name='user',
            name='num_phone',
        ),
        migrations.AddField(
            model_name='velo',
            name='station',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='velos', to='api.station'),
            preserve_default=False,
        ),
    ]
