# Generated by Django 4.2.3 on 2023-07-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_offreemp_id_dep_offreemp_id_struc'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichierbourse',
            name='PourPoste',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
