# Generated by Django 4.2.3 on 2023-07-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_fichierbourse_pourposte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichierbourse',
            name='Id_dep',
        ),
        migrations.AddField(
            model_name='fichierbourse',
            name='seminaire',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
