# Generated by Django 4.1.7 on 2023-04-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_station_remove_user_matricule_remove_user_num_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sold',
            field=models.IntegerField(default=10),
        ),
    ]
