# Generated by Django 4.2.3 on 2023-07-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_fichierbourse_id_dep_fichierbourse_seminaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcoursprof',
            name='id_Emp',
        ),
    ]
