# Generated by Django 4.2.3 on 2023-07-26 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_parcoursprof_id_emp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichierbourse',
            name='Telephone',
        ),
        migrations.RemoveField(
            model_name='parcoursprof',
            name='Periode',
        ),
        migrations.RemoveField(
            model_name='parcoursprof',
            name='id_fichier',
        ),
        migrations.AddField(
            model_name='parcoursprof',
            name='date_deb',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcoursprof',
            name='date_fin',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcoursprof',
            name='id_Emp',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fichierbourse',
            name='Commentaire',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fichierbourse',
            name='Etat_fichier',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fichierbourse',
            name='Reponse_DRH',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='fichierbourse',
            name='Reponse_commesion',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='fichierbourse',
            name='id_Emp',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fichierbourse',
            name='id_comm',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.commesion'),
        ),
    ]
