# Generated by Django 4.2.3 on 2023-07-26 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_fichierbourse_telephone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichierbourse',
            name='Commentaire',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fichierbourse',
            name='Etat_fichier',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fichierbourse',
            name='Reponse_DRH',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fichierbourse',
            name='Reponse_commesion',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fichierbourse',
            name='id_Emp',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fichierbourse',
            name='id_comm',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.commesion'),
        ),
    ]
