# Generated by Django 4.1.7 on 2023-05-03 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_location_reservation_alter_reservation_velo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='reservation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_alocate', to='api.reservation'),
        ),
    ]
