# Generated by Django 4.2.3 on 2023-07-29 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_fichierbourse_commentaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichierbourse',
            name='id_Offre',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.offreemp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichierbourse',
            name='submit_fichier',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='departement',
            name='id_struc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.structure'),
        ),
        migrations.AlterField(
            model_name='fichierbourse',
            name='id_Emp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fichierbourse',
            name='id_comm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.commesion'),
        ),
        migrations.AlterField(
            model_name='parcoursprof',
            name='id_Emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
