# Generated by Django 4.2.3 on 2023-07-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_fichierbourse_id_offre_fichierbourse_submit_fichier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_commission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_departement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_stricture',
            field=models.BooleanField(default=False),
        ),
    ]
