# Generated by Django 4.1.7 on 2023-05-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_location_date_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usage',
            field=models.IntegerField(default=0),
        ),
    ]
