# Generated by Django 4.2.3 on 2023-07-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_employee_is_commission_employee_is_departement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichierbourse',
            name='CompetanceRespo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichierbourse',
            name='NomRespo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichierbourse',
            name='PrenomRespo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fichierbourse',
            name='submit_fichier',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
