# Generated by Django 4.2.3 on 2023-07-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_fichierbourse_competancerespo_fichierbourse_nomrespo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichierbourse',
            name='Etat_fichier',
        ),
        migrations.AddField(
            model_name='fichierbourse',
            name='fanction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
