# Generated by Django 4.1.7 on 2023-05-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_velo_code_velo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos_user',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pos_user',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='velo',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
