# Generated by Django 4.2.3 on 2023-08-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_fichierbourse_etat_fichier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichierbourse',
            name='favorable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fichierbourse',
            name='response_Dep',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fichierbourse',
            name='CompetanceRespo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fichierbourse',
            name='NomRespo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fichierbourse',
            name='PrenomRespo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
