# Generated by Django 4.2.3 on 2023-08-16 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_fichierbourse_favorable_fichierbourse_response_dep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichierbourse',
            name='id_comm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_of_file', to=settings.AUTH_USER_MODEL),
        ),
    ]
