# Generated by Django 4.1.7 on 2023-05-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_user_sold_alter_user_usage_alter_velo_station"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
