# Generated by Django 4.2.3 on 2023-08-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_fichierbourse_id_comm'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichierbourse',
            name='response_Dir',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
