# Generated by Django 4.1.7 on 2023-05-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_user_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="usage",
            field=models.IntegerField(),
        ),
    ]
