# Generated by Django 4.2.3 on 2023-08-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_fichierbourse_response_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichierbourse',
            name='allright',
            field=models.BooleanField(default=False),
        ),
    ]
