# Generated by Django 4.2.3 on 2023-08-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_fichierbourse_allright'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichierbourse',
            name='allright',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
