# Generated by Django 4.1.7 on 2023-05-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_pos_user_velo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='velo_code',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='velo_name',
            field=models.CharField(default='hc', max_length=50),
            preserve_default=False,
        ),
    ]
