# Generated by Django 4.1.7 on 2023-05-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_reservation_velo_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='velo_code',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='velo_name',
            field=models.CharField(default='gc', max_length=50),
            preserve_default=False,
        ),
    ]
