# Generated by Django 4.1.7 on 2023-06-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_reservation_velo_code_reservation_velo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='reservation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='station',
            name='restauration',
            field=models.IntegerField(default=0),
        ),
    ]
